[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_tomb = "EbUS5R37dPQRdDKgh7Kju9JhwUg6FPB1fSRAjbUj29EQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm test"
